name: Document and Changelog

on:
  workflow_run:
    workflows: ["Generate and Release"]  # Trigger this workflow after the "Build Workflow"
    types:
      - completed

jobs:
  build-changelog:
    needs: [build-doc]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aesteri/testing_protoc
          ref: refs/heads/main

      - name: Save Commit Message
        id: save_commit
        run: |
          COMMIT_MESSAGES=$(git log -1 --pretty=format:"%s")
          LATEST_COMMIT_HASH=$(git log -1 --pretty=format:"%H")
          PARENT_COMMITS=$(git rev-list --parents -n 1 $LATEST_COMMIT_HASH)
          ACTUAL_COMMIT_HASH=$(echo $PARENT_COMMITS | cut -d' ' -f2)
          ACTUAL_COMMIT_MSG=$(git log --format=%B -n 1 $ACTUAL_COMMIT_HASH)
          ACTUAL_COMMIT_MSG=$(echo "$ACTUAL_COMMIT_MSG" | sed 's/^Merge pull request.*//' | tr -d '\n')
          echo "ACTUAL_COMMIT_MSG=${ACTUAL_COMMIT_MSG}" >> $GITHUB_ENV  

      - name: Generate changelog entry
        id: changelog
        run: |
          RELEASE_VERSION="${{ env.date }}"
          CHANGELOG_FILE="CHANGELOG.md"
          NEW_ENTRY="## [${RELEASE_VERSION}](https://github.com/${{ github.repository }}/releases/tag/${RELEASE_VERSION})\n\n"
          NEW_ENTRY+="* ${ACTUAL_COMMIT_MSG}\n\n"
          echo -e "${NEW_ENTRY}$(cat $CHANGELOG_FILE)" > $CHANGELOG_FILE

      - name: Upload changelog
        uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: CHANGELOG.md

  build-doc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [23.11]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aesteri/testing_protoc
          ref: refs/heads/main

      - name: Set up Protobuf tools and generate HTML file
        run: |
          sudo apt-get install -y --no-install-recommends protobuf-compiler
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          export PATH=$PATH:$HOME/go/bin
          mkdir -p docs
          protoc -I=proto --doc_out=./docs --doc_opt=html,index.html proto/*.proto

      - name: Upload doc html
        uses: actions/upload-artifact@v3
        with:
          name: doc
          path: ./docs/index.html

  upload-to-release:
    needs: [build-doc, build-changelog]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: aesteri/testing_protoc
          ref: refs/heads/main

      - name: Get latest release tag
        id: get_latest_release
        run: |
          TAG_NAME=$(curl -s \
            -H "Authorization: token ${{ secrets.MY_CUSTOM_GITHUB_TOKEN }}" \
            "https://api.github.com/repos/aesteri/testing_protoc/releases/latest" | jq -r .tag_name)
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          
      - name: Download artifact from build-docs
        uses: actions/download-artifact@v3
        with:
          name: doc

      - name: Download artifact from build-changelog
        uses: actions/download-artifact@v3
        with:
          name: changelog

      - name: Upload asset to existing release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }} 
          files: |
            index.html
            CHANGELOG.md