name: Document

on:
  workflow_run:
    workflows: ["Generate and Release"]
    types:
      - completed

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: tag-name-artifact

      - name: Set tag_name from file
        run: |
          TAG_NAME=$(cat tag_name.txt)
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
      
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.tag_name }}

      - name: Set up Protobuf tools and generate HTML file
        run: |
          mkdir -p docs
          mkdir -p proto/nanopb/google/protobuf
          
          sudo apt-get install -y --no-install-recommends protobuf-compiler
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@v1.5.1
          export PATH=$PATH:$HOME/go/bin
          
          curl -o proto/nanopb/google/protobuf/descriptor.proto https://raw.githubusercontent.com/nanopb/nanopb/master/generator/proto/google/protobuf/descriptor.proto
          curl -o proto/nanopb/nanopb.proto https://raw.githubusercontent.com/nanopb/nanopb/master/generator/proto/nanopb.proto
          protoc -I=proto -I=proto/nanopb --doc_out=./docs --doc_opt=html,${{ env.tag_name }}.html proto/*.proto
          
                
      - name: Upload asset to existing release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          files: |
            ./docs/${{ env.tag_name }}.html

      
